var RLANG = {
	html: 'Код',
	video: 'Відео',
	charmap: 'Спец. символ',
	image: 'Зображення',
	image_exist: 'Виберіть загружене раніше зображення',
	table: 'Таблиця',
	link: 'Псосилання',
	link_insert: 'Вставити посилання ...',
	unlink: 'Видалити посилання',
	fullscreen: 'На повний екран',
	styles: 'Стилі',
	paragraph: 'Звичайний текст',
	quote: 'Цитата',
	code: 'Код',
	header1: 'Заголовок 1',
	header2: 'Заголовок 2',
	format: 'Формат',
	bold:  'Потовщений',
	italic: 'Нахилений',
	superscript: 'Надстрічний',
	strikethrough: 'Закреслений',
	fontcolor: 'Колір тексту',
	backcolor: 'Фон тексту',
	removeformat: 'Очистити формат',
	cleanstyles: 'Очистити стилі MS Word',
	lists: 'Списки',
	unorderedlist: 'Звичайний список',
	orderedlist: 'Нумерований список',
	outdent: 'Зменшити відступ',
	indent: 'Збільшити відступ',
	align: 'Вирівнювання',
	align_left: 'По лівому краю',
	align_center: 'По центру',
	align_right: 'По правому краю',
	redo: 'Повтор',
	undo: 'Відміна',
	cut: 'Кат / Врізка',
	cancel: 'Відмінити',
	insert: 'Вставити',
	save: 'Зберегти',
	_delete: 'Знищити',
	add_cell: 'Добавити колонку',
	delete_cell: 'Видалити колонку',
	add_row: 'Добавити стрічку',
	delete_row: 'Видалити стрічку',
	thead: 'Заголовок',
	delete_table: 'Знищити таблицю',
	title: 'Підказка',
	image_view: 'Зкачати зображння',
	image_position: 'Обтікання текстом',
	none: 'нема',
	left: 'зліва',
	right: 'зправа',
	image_upload: 'або загрузіть нове',
	image_web_link: 'або впишіть посилання на зображення',
	text: 'Текст',
	mailto: 'Адреса эл. пошти',
	web: 'Адреса URL'
};